Spring:
  resources:
    # enable default static resources process
    add-mappings: true
    cache:
      cachecontrol:
        # cache
        max-age: 3600
    chain:
      # enable resources chain cache, default true
      cache: true
      # enable resources chain, default false
      enabled: true
      # enable compressed(gzip, brotli), default false
      compressed: true
      # enable h5 cache
      html-application-cache: true
#    static-location: classpath:/static/
  # Thymeleaf??
  Thymeleaf:
    # ????
    cache: false
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://url/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: 
    password: 
    # ???
    hikari:
      # ????
      pool-name: DataHikariCP
      # ???????
      minimum-idle: 5
      # ???????????????600000
      idle-timeout: 1800000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0?????????30??
      max-lifetime: 1800000
      # ?????????30000?30?
      connection-timeout: 3000
      # heartbeat
      connection-test-query: SELECT 1
#  redis config
  redis:
#    host
    host: 123.249.4.0
#    password
    password: 123456
#    port
    port: 6379
#    database
    database: 0
#    time to connect
    timeout: 10998ms
# rabbitmq
  rabbitmq:
    # host ip
    host: url
    # username
    username: guest
    # password
    password: guest
    # virtual-host
    virtual-host: /
    # port
    port: 5672
    listener:
      simple:
        # consumer min
        concurrency: 10
        # consumer max
        max-concurrency: 10
        # limit consumer get one message per time
        prefetch: 1
        # start with default start container. default true
        auto-startup: true
        # if consumer reject message, message requeue, default true
        default-requeue-rejected: true
    template:
      retry:
        # enable retry
        enabled: true
        # retry time, default 1000ms
        initial-interval: 1000ms
        # max retry times, default 3
        max-attempts: 3
        # max retry interval, default 10000ms
        max-interval: 10000ms
        # retry interval multiplier, first = 10, second = 20 if multiplier = 2
        multiplier: 1


    lettuce:
      pool:
#        max time to wait default -1
        max-wait: 10000ms
#        max active connections default 8
        max-active: 8
#        max idle connections defalut 8
        max-idle: 200
#        min idle connections defalut 8
        min-idle: 5



  # mybatis-plus
  mybatis-plus:
    # ??Mapper.xml????
    mapper-locations: classpath*:/mapper/*.xml
    # ??MyBatis?????????????????
    type-aliases-package: com.example.seckill.pojo
  # mybatis sql??????????? ?
  logging:
    level:
      com.example.sekill.mapper: debug
